version: 0.0
os: linux

file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /home/ubuntu/app

permissions:
  - object: /home/ubuntu/app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root   # cleanup often needs root to remove files created by root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu # safe to run npm install as ubuntu

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
